Repository Nexters/Jaknaeso-web, pull requests merged in 2025-02, with the labels that each got.

#19 feat: svgr 세팅 및 Layout UI 작업
  .storybook/main.ts
  next.config.ts
  package.json
  src/app/(route)/(home)/components/Test.tsx
  src/app/(route)/(home)/layout.tsx
  src/app/(route)/(home)/page.tsx
  src/app/(route)/game/page.tsx
  src/app/(route)/mypage/layout.tsx
  src/app/(route)/mypage/page.tsx
  src/app/(route)/report/analysis/page.tsx
  src/app/(route)/report/layout.tsx
  src/app/(route)/report/questions/page.tsx
  src/app/globals.scss
  src/app/layout.tsx
  src/assets/icons/arrows/arrow-down2.svg
  src/assets/icons/arrows/arrow-left.svg
  src/assets/icons/arrows/arrow-left2.svg
  src/assets/icons/arrows/arrow-up2.svg
  src/assets/icons/arrows/index.ts
  src/assets/icons/communication/index.ts
  src/assets/icons/communication/profile.svg
  src/assets/icons/files/file-document.svg
  src/assets/icons/files/index.ts
  src/assets/icons/general/home.svg
  src/assets/icons/general/index.ts
  src/assets/icons/general/lock-off.svg
  src/assets/icons/general/lock.svg
  src/assets/icons/index.ts
  src/assets/icons/interface/close.svg
  src/assets/icons/interface/index.ts
  src/components/Button/Button.module.scss
  src/components/Button/Button.stories.ts
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/Layout/Footer/Footer.module.scss
  src/components/Layout/Footer/Footer.tsx
  src/components/Layout/Footer/FooterLayout.tsx
  src/components/Layout/Footer/index.ts
  src/components/Layout/TopBar/TopBar.module.scss
  src/components/Layout/TopBar/TopBar.tsx
  src/components/Layout/TopBar/index.ts
  src/constants/index.ts
  src/constants/routes.ts
  src/styles/scss/utils/_mixins.scss
  src/types/svgr.d.ts
  tsconfig.json
  yarn.lock
Labels: feature

#27 feat: 홈페이지 퍼블리싱
  package.json
  src/app/(route)/(home)/components/Drawer/Content.tsx
  src/app/(route)/(home)/components/Drawer/Drawer.module.scss
  src/app/(route)/(home)/components/Drawer/Drawer.tsx
  src/app/(route)/(home)/components/Drawer/Footer.tsx
  src/app/(route)/(home)/components/Drawer/Handle.tsx
  src/app/(route)/(home)/components/Drawer/index.ts
  src/app/(route)/(home)/components/Drawer/useDrawer.ts
  src/app/(route)/(home)/page.module.scss
  src/app/(route)/(home)/page.tsx
  src/app/(route)/mypage/components/ProfileCard.tsx
  src/app/(route)/mypage/components/UserActionFooter.tsx
  src/app/(route)/mypage/components/UserSettings.tsx
  src/app/(route)/mypage/page.tsx
  src/app/(route)/report/questions/page.tsx
  src/assets/icons/interface/index.ts
  src/assets/icons/interface/line.svg
  src/components/Capsule/Capsule.module.scss
  src/components/Capsule/Capsule.tsx
  src/components/LockBtn/LockBtn.tsx
  src/hooks/index.ts
  src/hooks/usePreviousValue.ts
  yarn.lock
Labels: feature

#28 style: pretendard 폰트 적용
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  src/app/globals.scss
Labels: style

#31 feat: UT 전 홈페이지 Drawer 기능 수정
  src/app/(route)/(home)/components/Drawer/Drawer.module.scss
  src/app/(route)/(home)/components/Drawer/Drawer.tsx
  src/app/(route)/(home)/components/Drawer/Handle.tsx
  src/app/(route)/(home)/page.module.scss
  src/app/(route)/(home)/page.tsx
  src/components/Layout/Footer/Footer.module.scss
  src/styles/scss/base/_typography.scss
  src/styles/scss/base/_variables.scss
Labels: feature

#36 feat: 가치관 게임 - 슬라이더 퍼블리싱 및 UT 세팅
  src/app/(route)/(home)/page.tsx
  src/app/(route)/game/components/FlipCard/FlipCard.module.scss
  src/app/(route)/game/components/FlipCard/FlipCard.tsx
  src/app/(route)/game/components/FlipCard/index.ts
  src/app/(route)/game/components/GameBottomSheet/GameBottomSheet.module.scss
  src/app/(route)/game/components/GameBottomSheet/GameBottomSheet.tsx
  src/app/(route)/game/components/GameBottomSheet/index.ts
  src/app/(route)/game/components/GameLayout/GameLayout.module.scss
  src/app/(route)/game/components/GameLayout/GameLayout.tsx
  src/app/(route)/game/components/GameLayout/index.ts
  src/app/(route)/game/page.module.scss
  src/app/(route)/game/page.tsx
  src/app/(route)/select/page.tsx
  src/components/Slider/Slider.module.scss
  src/components/Slider/Slider.tsx
  src/components/Slider/index.ts
  src/constants/routes.ts
  yarn.lock
Labels: feature

#33 feat: TabNav 컴포넌트
  src/app/(route)/report/analysis/page.tsx
  src/app/(route)/report/layout.module.scss
  src/app/(route)/report/layout.tsx
  src/app/(route)/report/questions/page.module.scss
  src/app/(route)/report/questions/page.tsx
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/TabNav/TabNav.module.scss
  src/components/TabNav/TabNav.tsx
  src/components/TabNav/index.ts
Labels: feature

#38 feat: 1차 QA - 홈 페이지 반영
  src/app/(route)/(home)/components/Drawer/Drawer.module.scss
  src/app/(route)/(home)/components/Drawer/Drawer.tsx
  src/app/(route)/(home)/components/Drawer/Handle.tsx
  src/app/(route)/(home)/page.module.scss
  src/app/(route)/(home)/page.tsx
  src/app/(route)/game/complete/page.tsx
Labels: feature

#42 feat: UT 전 리뷰 반영
  src/app/(route)/game/complete/page.tsx
  src/app/(route)/game/components/GameLayout/GameLayout.module.scss
  src/app/(route)/mypage/components/UserActionFooter.tsx
  src/app/(route)/report/layout.tsx
  yarn.lock
Labels: feature

#13 feat: 카카오 로그인 구현
  next.config.ts
  package.json
  src/app/(route)/(home)/page.tsx
  src/app/(route)/game/complete/page.tsx
  src/app/(route)/game/components/GameBottomSheet/GameBottomSheet.tsx
  src/app/(route)/game/page.tsx
  src/app/(route)/login/kakao/page.tsx
  src/app/(route)/login/layout.tsx
  src/app/(route)/login/login.module.scss
  src/app/(route)/login/page.tsx
  src/app/(route)/mypage/components/UserActionFooter.tsx
  src/app/(route)/report/layout.tsx
  src/app/(route)/report/questions/page.tsx
  src/app/(route)/select/page.tsx
  src/app/layout.tsx
  src/assets/buttons/apple_login_btn.svg
  src/assets/buttons/index.ts
  src/assets/buttons/kakao_login_btn.svg
  src/components/KakaoScript/KakaoScript.tsx
  src/components/KakaoScript/index.ts
  src/components/TabNav/TabNav.tsx
  src/libs/api/api.client.ts
  src/libs/api/api.server.ts
  src/libs/api/api.ts
  src/libs/api/client.ts
  src/libs/config.ts
  src/libs/cookie/cookieKey.ts
  src/libs/cookie/manageCookie.client.ts
  src/libs/cookie/manageCookie.server.ts
  src/libs/index.ts
  src/middleware.ts
  src/query-hooks/useAuth/api.ts
  src/query-hooks/useAuth/index.ts
  src/query-hooks/useAuth/keys.ts
  src/query-hooks/useAuth/types.ts
  src/query-hooks/useTest/api.ts
  src/types/global.d.ts
  src/types/index.ts
  src/types/responeDTO.ts
  src/utils/modules/api.client.ts
  src/utils/modules/api.server.ts
Labels: feature

#49 feat: 홈 페이지 survey API 연동
  src/app/(route)/(home)/components/Drawer/Drawer.tsx
  src/app/(route)/(home)/components/Drawer/index.ts
  src/app/(route)/(home)/components/Drawer/useDrawer.ts
  src/app/(route)/(home)/components/Page/Content.tsx
  src/app/(route)/(home)/components/Page/Page.module.scss
  src/app/(route)/(home)/components/Page/Page.tsx
  src/app/(route)/(home)/components/Page/Title.tsx
  src/app/(route)/(home)/components/Page/index.ts
  src/app/(route)/(home)/page.tsx
  src/components/LockBtn/LockBtn.tsx
  src/components/ReactQuery/PrefetchHydration.tsx
  src/components/ReactQuery/index.ts
  src/query-hooks/useSurvey/api.client.ts
  src/query-hooks/useSurvey/api.server.ts
  src/query-hooks/useSurvey/index.ts
  src/query-hooks/useSurvey/keys.ts
  src/query-hooks/useSurvey/types.ts
  src/utils/createQueryKey.ts
Labels: feature

#52 feat: 멤버 정보 API 연동 및 전역 상태 관리
  package.json
  src/app/(route)/mypage/components/UserActionFooter.tsx
  src/app/(route)/mypage/page.tsx
  src/query-hooks/useAuth/api.ts
  src/query-hooks/useAuth/index.ts
  src/query-hooks/useAuth/keys.ts
  src/query-hooks/useMember/api.client.ts
  src/query-hooks/useMember/api.server.ts
  src/query-hooks/useMember/index.ts
  src/query-hooks/useMember/keys.ts
  src/query-hooks/useMember/types.ts
  src/stores/index.ts
  src/stores/useMember.ts
  src/utils/index.ts
  yarn.lock
Labels: feature

#69 feat : 제출 오류 수정 및 이중택일 게임 페이지 디자인 변경사항 반영
  src/app/(route)/game/[bundleId]/components/FlipCard/FlipCard.module.scss
  src/app/(route)/game/[bundleId]/components/FlipCard/FlipCard.tsx
  src/app/(route)/game/[bundleId]/components/GameBottomSheet/GameBottomSheet.tsx
  src/app/(route)/game/[bundleId]/components/GameClientPage/GameClientPage.tsx
  src/app/(route)/game/[bundleId]/components/GameLayout/GameLayout.module.scss
  src/app/(route)/game/[bundleId]/components/GameLayout/GameLayout.tsx
  src/assets/icons/interface/index.ts
  src/assets/icons/interface/sync.svg
  src/query-hooks/useSurvey/api.client.ts
  src/query-hooks/useSurvey/index.ts
  src/query-hooks/useSurvey/types.ts
Labels: feature

#58 feat: 1차 UT QA 홈 페이지 반영
  src/app/(route)/(home)/components/Page/Content.tsx
  src/app/(route)/mypage/components/UserSettings.tsx
  src/app/(route)/mypage/page.tsx
  src/app/(route)/report/analysis/page.tsx
  src/app/(route)/report/components/CharacterSelectBottomSheet/CharacterSelectBottomSheet.tsx
  src/app/(route)/report/components/CharacterSelectButton/CharacterSelectButton.tsx
  src/app/(route)/report/components/CharacterSelectLayout/CharacterSelectLayout.tsx
  src/app/(route)/report/questions/layout.tsx
  src/app/(route)/report/questions/page.tsx
  src/app/(route)/term/page.tsx
  src/app/layout.tsx
  src/components/Card/Card.tsx
  src/components/Toast/Toast.module.scss
  src/components/Toast/Toast.tsx
  src/components/Toast/index.ts
  src/hooks/index.ts
  src/hooks/useToast.ts
  src/query-hooks/useCharacter/api.client.ts
  src/query-hooks/useCharacter/api.server.ts
  src/query-hooks/useCharacter/index.ts
  src/stores/index.ts
  src/stores/useToast.ts
Labels: feature

#63 feat: 2차 MVP - 캐릭터 분석 페이지 퍼블리싱
  package.json
  src/app/(route)/report/analysis/components/Contents/CharacterContent/CharacterContent.module.scss
  src/app/(route)/report/analysis/components/Contents/CharacterContent/CharacterContent.tsx
  src/app/(route)/report/analysis/components/Contents/CharacterContent/index.ts
  src/app/(route)/report/analysis/components/Contents/ChartContent/ChartContent.module.scss
  src/app/(route)/report/analysis/components/Contents/ChartContent/ChartContent.tsx
  src/app/(route)/report/analysis/components/Contents/ChartContent/RadarChart.tsx
  src/app/(route)/report/analysis/components/Contents/ChartContent/index.ts
  src/app/(route)/report/analysis/components/Contents/RetrospectiveContent/RetrospectiveContent.module.scss
  src/app/(route)/report/analysis/components/Contents/RetrospectiveContent/RetrospectiveContent.tsx
  src/app/(route)/report/analysis/components/Contents/RetrospectiveContent/index.ts
  src/app/(route)/report/analysis/components/Page/Page.module.scss
  src/app/(route)/report/analysis/components/Page/Page.tsx
  src/app/(route)/report/analysis/components/Page/index.ts
  src/app/(route)/report/analysis/page.tsx
  src/app/(route)/report/components/CharacterTabNav/CharacterTabNav.tsx
  src/app/(route)/report/layout.module.scss
  src/app/globals.scss
  src/components/BottomSheet/BottomSheet.module.scss
  src/components/Diver/Diver.module.scss
  src/components/Diver/Diver.tsx
  src/components/Diver/index.ts
  src/styles/scss/utils/_mixins.scss
  yarn.lock
Labels: feature

#84 feat: 로그인 API 수정 반영 및 온보딩 페이지 미들웨어 처리
  src/app/(route)/onboarding/page.tsx
  src/app/globals.scss
  src/constants/routes.ts
  src/libs/cookie/cookieKey.ts
  src/libs/cookie/manageCookie.client.ts
  src/libs/cookie/manageCookie.server.ts
  src/middleware.ts
  src/query-hooks/useAuth/api.ts
  src/query-hooks/useAuth/index.ts
  src/query-hooks/useAuth/types.ts
Labels: feature

#86 feat : 서비스 온보딩 퍼블리싱 및 온보딩 페이지 API 연결
  package.json
  src/app/(route)/game/[bundleId]/components/GameClientPage/GameClientPage.tsx
  src/app/(route)/onboarding/components/OnboardingClientPage/OnboardingClientPage.tsx
  src/app/(route)/onboarding/game/complete/page.module.scss
  src/app/(route)/onboarding/game/complete/page.tsx
  src/app/(route)/onboarding/game/components/OnboardingClientPage/OnboardingClientPage.module.scss
  src/app/(route)/onboarding/game/components/OnboardingClientPage/OnboardingClientPage.tsx
  src/app/(route)/onboarding/game/components/OnboardingClientPage/index.ts
  src/app/(route)/onboarding/game/page.tsx
  src/app/(route)/onboarding/page.module.scss
  src/app/(route)/onboarding/page.tsx
  src/app/globals.scss
  src/app/loading.tsx
  src/components/Slider/Slider.tsx
  src/constants/routes.ts
  src/middleware.ts
  src/query-hooks/useSurvey/api.client.ts
  src/query-hooks/useSurvey/index.ts
  src/query-hooks/useSurvey/types.ts
  yarn.lock
Labels: feature

#87 feat: 모달 컴포넌트 구현 및 마이페이지 적용
  src/app/(route)/mypage/components/UserActionFooter.module.scss
  src/app/(route)/mypage/components/UserActionFooter.tsx
  src/app/(route)/mypage/components/UserSettings.module.scss
  src/components/BottomSheet/BottomSheet.tsx
  src/components/Modal/Footer.tsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/index.ts
Labels: feature

#90 feat: 이중택일 새 버전 컴포넌트 퍼블리싱
  src/app/(route)/game/[bundleId]/components/SelectCardList/SelectCardList.module.scss
  src/app/(route)/game/[bundleId]/components/SelectCardList/SelectCardList.tsx
  src/app/(route)/game/[bundleId]/components/SelectCardList/index.ts
Labels: feature

#97 feat: QA 반영 - 홈 및 캐릭터 분석 페이지
  src/app/(route)/(home)/components/Page/Title.tsx
  src/app/(route)/onboarding/game/complete/page.tsx
  src/app/(route)/report/components/AnalysisTab/AnalysisContent/CharacterContent/CharacterContent.tsx
  src/app/(route)/report/components/QuestionsTab/QuestionsTab.tsx
  src/app/(route)/report/components/ReportClientPage/CharacterBottomSheet.tsx
  src/app/(route)/report/components/ReportClientPage/ReportClientPage.tsx
  src/query-hooks/useCharacter/api.client.ts
  src/query-hooks/useCharacter/api.server.ts
  src/query-hooks/useCharacter/types.ts
  src/query-hooks/useSurvey/api.client.ts
  src/query-hooks/useSurvey/api.server.ts
  src/query-hooks/useSurvey/index.ts
Labels: feature

#99 [feat] QA 반영 - 홈 및 분석 페이지 스타일 수정 및 조사(을/를) 통일
  src/app/(route)/(home)/components/Page/Page.module.scss
  src/app/(route)/(home)/components/Page/Page.tsx
  src/app/(route)/report/components/AnalysisTab/AnalysisContent/ChartContent/ChartContent.module.scss
  src/app/(route)/report/components/AnalysisTab/AnalysisContent/ChartContent/ChartContent.tsx
  src/app/(route)/report/components/AnalysisTab/AnalysisContent/InfoContent/InfoContent.tsx
  src/app/(route)/report/components/AnalysisTab/AnalysisTab.tsx
  src/app/(route)/report/components/QuestionsTab/QuestionsTab.module.scss
  src/app/(route)/report/components/ReportClientPage/ReportClientPage.module.scss
  src/assets/lottie/safety.json
  src/components/Card/Card.module.scss
  src/components/Card/Card.tsx
  src/components/Diver/index.ts
  src/components/Divider/Divider.module.scss
  src/components/Divider/Divider.tsx
  src/components/Divider/index.ts
  src/components/Layout/Footer/Footer.tsx
  src/utils/checkLetter.ts
  src/utils/index.ts
Labels: feature

#101 bug: 온보딩 게임 완료 후 캐릭터 분석 결과 안보이는 문제 해결
  src/app/(route)/report/components/QuestionsTab/QuestionsTab.tsx
  src/app/(route)/report/components/ReportClientPage/CharacterBottomSheet.tsx
  src/app/(route)/report/components/ReportClientPage/ReportClientPage.tsx
  src/app/(route)/report/page.tsx
  src/query-hooks/useCharacter/api.client.ts
  src/query-hooks/useSurvey/index.ts
  src/stores/useCharacter.ts
Labels: bug

#103 chore: QA 반영 - 토스트 및 게임 카드 스타일 및 텍스트 수정
  src/app/(route)/game/[bundleId]/components/FlipCard/FlipCard.tsx
  src/app/(route)/game/complete/page.tsx
  src/app/(route)/report/components/EmptyTab/EmptyTab.module.scss
  src/app/globals.scss
  src/components/Toast/Toast.module.scss
Labels: chore

#104 feat: 홈 바텀 시트 터치 액션 동작 안되는 문제 해결 및 회고 페이지 라우팅 추가
  src/app/(route)/(home)/components/Drawer/Drawer.module.scss
  src/app/(route)/(home)/components/Drawer/Drawer.tsx
  src/app/(route)/(home)/components/Page/Content.tsx
  src/app/(route)/(home)/components/Page/Page.module.scss
  src/app/(route)/(home)/components/Page/Page.tsx
  src/app/(route)/game/[bundleId]/components/GameBottomSheet/GameBottomSheet.module.scss
  src/app/(route)/report/components/QuestionsTab/QuestionsTab.module.scss
  src/app/(route)/report/components/QuestionsTab/QuestionsTab.tsx
  src/app/(route)/report/components/ReportClientPage/ReportClientPage.tsx
Labels: feature
